update test.yml for better cache handling

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,10 +21,12 @@ jobs:
         with:
           python-version: "3.11"
           cache: "pip"
+          cache-dependency-path: "requirements.txt"
 
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
+          if [ ! -f requirements.txt ]; then echo "requirements.txt not found!" && exit 1; fi
           pip install -r requirements.txt
 
       - name: Run Tests
